id = "mdx"
name = "MDX"
version = "0.0.1"
schema_version = 1
authors = ["Jason Antwi-Appah <hey@jasonaa.me>"]
description = "MDX language support"
repository = "https://github.com/jasonappah/zed-mdx"

[grammars.mdx]
repository = "https://github.com/jlopezcur/tree-sitter-mdx"
commit = "df43681bff333228fa60b69c09a1e7a6f9ed1610"

[language_servers.mdx-language-server]
name = "MDX Language Server"
language = "MDX"