name = "MDX"
grammar = "mdx"
path_suffixes = ["mdx"]
word_characters = ["-"]
block_comment = ["<!-- ", " -->"]

brackets = [
    { start = "{", end = "}", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = true },
    { start = "\"", end = "\"", close = false, newline = false },
    { start = "'", end = "'", close = false, newline = false },
    { start = "`", end = "`", close = false, newline = false },
]

tab_size = 2
soft_wrap = "preferred_line_length"
prettier_parser_name = "mdx"
